name: macOS build

on: push # testing only
# on: workflow_dispatch # eventually

# jobs:
#   build:
#     runs-on: "macos-latest"
#     steps:
#     - uses: actions/checkout@v6
#     - uses: actions/checkout@v6
#       with:
#         path: SolLevante
#         ref: sollevante
#     - run: xz --decompress SolLevante/SolLevante.y4m.xz
#     - uses: ilammy/setup-nasm@v1
#     - run: Build/linux/build.sh --verbose --native --static --release --enable-lto --enable-pgo --pgo-videos="$(realpath SolLevante)"
#     - uses: actions/upload-artifact@v7
#       with:
#         path: Bin/Release/SvtAv1EncApp

jobs:
  build:
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v6
    - uses: actions/checkout@v6
      with:
        path: SolLevante
        ref: sollevante
    - run: xz --decompress SolLevante/SolLevante.y4m.xz
    - uses: ilammy/setup-nasm@v1
    - uses: ConorMacBride/install-package@v1
      with:
        brew: llvm lld
    - run: PATH="/opt/homebrew/opt/llvm/bin:$PATH" LDFLAGS="-L/opt/homebrew/opt/llvm/lib -fuse-ld=lld" CPPFLAGS="-I/opt/homebrew/opt/llvm/include" CMAKE_PREFIX_PATH="/opt/homebrew/opt/llvm" Build/linux/build.sh --verbose --native --static --release --enable-lto --enable-pgo --pgo-videos="$(realpath SolLevante)"
    - uses: actions/upload-artifact@v7
      with:
        path: Bin/Release/SvtAv1EncApp
