# To build it yourself, always use clang over gcc or msvc. It's plain faster.
# Run `Build/linux/build.sh --native --static --release --enable-lto --enable-pgo` to build a decent binary.
# For more optimised building, check how we do it below. Everything here is not selected on a whim but tested to indeed produce a faster binary thanks to everybody in this community.
# Thanks to studies and contributions from afed, Ironclad, Itachi Uchiha, Miss Ashenlight, SwareJonge, Trix, Yiss and other people in the community to discover the method to build the fastest binary.

name: pgo-build
on: push # testing only
# on: workflow_dispatch # eventually

jobs:
  tag:
    runs-on: "ubuntu-latest"
    outputs:
      tag: ${{ steps.generate.outputs.tag }}
    steps:
    - uses: actions/checkout@v7
    - id: generate
      run: echo tag=v$(git log -1 "--date=format:%y%m%d" "--format=2.3.%ad") >> "$GITHUB_OUTPUT"

  release:
    needs: tag
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v7
    - run: GH_TOKEN=${{ github.token }} gh release delete ${{ needs.tag.outputs.tag }} --cleanup-tag
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        target_commitish: ${{ github.sha }}
        name: 5fish/SVT-AV1 ${{ needs.tag.outputs.tag }}
        body: |
          Ref `${{ github.ref }}` | Commit `${{ github.sha }}`  
          macOS arm64 | LLVM Project Clang & LLD | armv9.2-a + apple-m3 | PGO  

          Thanks to studies and contributions from afed, Ironclad, Itachi Uchiha, Miss Ashenlight, SwareJonge, Trix, Yiss and other people in the community to discover the method to build the fastest binary. If you need to build a binary yourself, check [the note](https://github.com/5fish/SVT-AV1/blob/${{ github.sha }}/.github/workflows/pgo-build.yml#L1-L4) in the building script.  
        prerelease: false
        make_latest: "true"

  build-macos:
    needs: [tag, release]
    runs-on: "macos-latest"
    steps:
    - uses: actions/checkout@v7
    - uses: actions/checkout@v7
      with:
        path: SolLevante
        ref: sollevante
    - run: xz --decompress SolLevante/SolLevante.y4m.xz
    - run: sysctl -a | grep machdep.cpu
    - uses: ilammy/setup-nasm@v1
    - uses: ConorMacBride/install-package@v1
      with:
        brew: llvm lld
    - run: PATH="/opt/homebrew/opt/llvm/bin:$PATH" CMAKE_PREFIX_PATH="/opt/homebrew/opt/llvm" CFLAGS="-I/opt/homebrew/opt/llvm/include -march=armv9.2-a -mtune=apple-m3" CPPFLAGS="-I/opt/homebrew/opt/llvm/include -march=armv9.2-a -mtune=apple-m3" LDFLAGS="-L/opt/homebrew/opt/llvm/lib -fuse-ld=lld" Build/linux/build.sh --verbose --static --release --enable-pgo --pgo-videos="$(realpath SolLevante)"
    - run: cd Bin/Release && tar cJf macOS_arm64_armv9.2-a+apple-m3.tar.xz SvtAv1EncApp && cd ../..
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: Bin/Release/macOS_arm64_armv9.2-a+apple-m3.tar.xz

  # Apple LLVM slightly slower
  # build-macos:
  #   runs-on: "macos-latest"
  #   steps:
  #   - uses: actions/checkout@v7
  #   - uses: actions/checkout@v7
  #     with:
  #       path: SolLevante
  #       ref: sollevante
  #   - run: xz --decompress SolLevante/SolLevante.y4m.xz
  #   - uses: ilammy/setup-nasm@v1
  #   - run: Build/linux/build.sh --verbose --native --static --release --enable-lto --enable-pgo --pgo-videos="$(realpath SolLevante)"
  #   - uses: actions/upload-artifact@v7
  #     with:
  #       path: Bin/Release/SvtAv1EncApp
